#include <cudro/codegen_c.hpp>

#include <cudro/dag.hpp>
#include <cudro/ad.hpp>
#include <cudro/lower.hpp>

#include <vector>
#include <string>
#include <sstream>
#include <iomanip>
#include <unordered_map>
#include <algorithm>

namespace cudro {

// Helper to get a unique variable name for a DAG node
static std::string node_var_name(int idx) {
    return "n" + std::to_string(idx);
}

static void emit_mat4_identity(std::ostringstream& out, const std::string& name) {
    out << "    float " << name << "[4][4] = {\n";
    out << "        {1,0,0,0},\n";
    out << "        {0,1,0,0},\n";
    out << "        {0,0,1,0},\n";
    out << "        {0,0,0,1}\n";
    out << "    };\n";
}

static void emit_vec3(std::ostringstream& out, const std::string& name, const Vec3& v) {
    out << "    float " << name << "[3] = {"
        << v.x << "f, " << v.y << "f, " << v.z << "f};\n";
}

static void emit_vec4(std::ostringstream& out, const std::string& name, const Vec3& v, double w) {
    out << "    float " << name << "[4] = {"
        << v.x << "f, " << v.y << "f, " << v.z << "f, " << w << "f};\n";
}

std::string generate_scalar_c(const LowerResult& lower_result, const CodegenOptions& opts) {
    const ExprDAG& dag = lower_result.dag;
    int num_inputs = lower_result.num_inputs;
    int num_constraints = lower_result.constraint_outputs.size();
    const auto& constraint_outputs = lower_result.constraint_outputs;
    
    std::ostringstream out;
    out << std::fixed << std::setprecision(6);
    
    // Header
    out << "// Generated by Cudro - do not edit\n";
    out << "#include <math.h>\n";
    out << "#include <stddef.h>\n\n";
    
    // Function signature
    out << "void project(const float* q, int n, float* out_g) {\n";
    
    // Input copy
    out << "    // Input copy\n";
    for (int i = 0; i < num_inputs; ++i) {
        out << "    float q" << i << " = q[" << i << "];\n";
    }
    out << "\n";
    
    // Track node values
    out << "    // Node values\n";
    for (int i = 0; i < dag.size(); ++i) {
        const Node& n = dag[i];
        std::string var = "n" + std::to_string(i);
        if (n.kind == NodeKind::Input) {
            out << "    float " << var << " = q" << n.input_index << ";\n";
        } else if (n.kind == NodeKind::Constant) {
            out << "    float " << var << " = " << n.constant_value << "f;\n";
        } else if (n.kind == NodeKind::Mat4 || n.kind == NodeKind::Mat4Identity ||
                   n.kind == NodeKind::RotX || n.kind == NodeKind::RotY || n.kind == NodeKind::RotZ ||
                   n.kind == NodeKind::RotAxis || n.kind == NodeKind::Translate || n.kind == NodeKind::MatMul) {
            out << "    float " << var << "[4][4];\n";
        } else if (n.kind == NodeKind::Vec4 || n.kind == NodeKind::MatVecMul) {
            out << "    float " << var << "[4];\n";
        } else if (n.kind == NodeKind::Vec3 || n.kind == NodeKind::SubVec3) {
            out << "    float " << var << "[3];\n";
        } else {
            out << "    float " << var << ";\n";
        }
    }
    out << "\n";
    
    // Evaluate DAG in topological order
    out << "    // Evaluate DAG\n";
    for (int i = 0; i < dag.size(); ++i) {
        const Node& n = dag[i];
        std::string var = "n" + std::to_string(i);
        
        switch (dag[i].kind) {
            case NodeKind::Input:
            case NodeKind::Constant:
                break;
                
            case NodeKind::Add: {
                out << "    " << node_var_name(i) << " = " 
                    << node_var_name(dag[i].operands[0]) << " + " 
                    << node_var_name(dag[i].operands[1]) << ";\n";
                break;
            }
            case NodeKind::Sub: {
                out << "    " << node_var_name(i) << " = " 
                    << node_var_name(dag[i].operands[0]) << " - " 
                    << node_var_name(dag[i].operands[1]) << ";\n";
                break;
            }
            case NodeKind::Mul: {
                out << "    " << node_var_name(i) << " = " 
                    << node_var_name(dag[i].operands[0]) << " * " 
                    << node_var_name(dag[i].operands[1]) << ";\n";
                break;
            }
            case NodeKind::Div: {
                out << "    " << node_var_name(i) << " = " 
                    << node_var_name(dag[i].operands[0]) << " / " 
                    << node_var_name(dag[i].operands[1]) << ";\n";
                break;
            }
            case NodeKind::Neg: {
                out << "    " << node_var_name(i) << " = -" 
                    << node_var_name(dag[i].operands[0]) << ";\n";
                break;
            }
            case NodeKind::Cos: {
                out << "    " << node_var_name(i) << " = cosf(" 
                    << node_var_name(dag[i].operands[0]) << ");\n";
                break;
            }
            case NodeKind::Sin: {
                out << "    " << node_var_name(i) << " = sinf(" 
                    << node_var_name(dag[i].operands[0]) << ");\n";
                break;
            }
            case NodeKind::Vec3: {
                out << "    " << node_var_name(i) << "[0] = " << node_var_name(dag[i].operands[0]) << "; "
                    << node_var_name(i) << "[1] = " << node_var_name(dag[i].operands[1]) << "; "
                    << node_var_name(i) << "[2] = " << node_var_name(dag[i].operands[2]) << ";\n";
                break;
            }
            case NodeKind::Vec4: {
                out << "    " << node_var_name(i) << "[0] = " << node_var_name(dag[i].operands[0]) << "; "
                    << node_var_name(i) << "[1] = " << node_var_name(dag[i].operands[1]) << "; "
                    << node_var_name(i) << "[2] = " << node_var_name(dag[i].operands[2]) << "; "
                    << node_var_name(i) << "[3] = " << node_var_name(dag[i].operands[3]) << ";\n";
                break;
            }
            case NodeKind::Mat4: {
                for (int r = 0; r < 4; ++r) {
                    for (int c = 0; c < 4; ++c) {
                        int idx = n.operands[r*4 + c];
                        out << "    " << node_var_name(i) << "[" << r << "][" << c << "] = " << node_var_name(idx) << ";\n";
                    }
                }
                break;
            }
            case NodeKind::Mat4Identity: {
                for (int r = 0; r < 4; ++r) {
                    for (int c = 0; c < 4; ++c) {
                        out << "    " << node_var_name(i) << "[" << r << "][" << c << "] = " << (r == c ? "1.0f" : "0.0f") << ";\n";
                    }
                }
                break;
            }
            case NodeKind::RotX: {
                out << "    {\n";
                out << "        float cx = cosf(" << node_var_name(dag[i].operands[0]) << ");\n";
                out << "        float sx = sinf(" << node_var_name(dag[i].operands[0]) << ");\n";
                out << "        " << node_var_name(i) << "[0][0] = 1.0f; " << node_var_name(i) << "[0][1] = 0.0f; " 
                    << node_var_name(i) << "[0][2] = 0.0f; " << node_var_name(i) << "[0][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[1][0] = 0.0f; " << node_var_name(i) << "[1][1] = cx; " 
                    << node_var_name(i) << "[1][2] = -sx; " << node_var_name(i) << "[1][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[2][0] = 0.0f; " << node_var_name(i) << "[2][1] = sx; " 
                    << node_var_name(i) << "[2][2] = cx; " << node_var_name(i) << "[2][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[3][0] = 0.0f; " << node_var_name(i) << "[3][1] = 0.0f; " 
                    << node_var_name(i) << "[3][2] = 0.0f; " << node_var_name(i) << "[3][3] = 1.0f;\n";
                out << "    }\n";
                break;
            }
            case NodeKind::RotY: {
                out << "    {\n";
                out << "        float cy = cosf(" << node_var_name(dag[i].operands[0]) << ");\n";
                out << "        float sy = sinf(" << node_var_name(dag[i].operands[0]) << ");\n";
                out << "        " << node_var_name(i) << "[0][0] = cy; " << node_var_name(i) << "[0][1] = 0.0f; " 
                    << node_var_name(i) << "[0][2] = sy; " << node_var_name(i) << "[0][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[1][0] = 0.0f; " << node_var_name(i) << "[1][1] = 1.0f; " 
                    << node_var_name(i) << "[1][2] = 0.0f; " << node_var_name(i) << "[1][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[2][0] = -sy; " << node_var_name(i) << "[2][1] = 0.0f; " 
                    << node_var_name(i) << "[2][2] = cy; " << node_var_name(i) << "[2][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[3][0] = 0.0f; " << node_var_name(i) << "[3][1] = 0.0f; " 
                    << node_var_name(i) << "[3][2] = 0.0f; " << node_var_name(i) << "[3][3] = 1.0f;\n";
                out << "    }\n";
                break;
            }
            case NodeKind::RotZ: {
                out << "    {\n";
                out << "        float cz = cosf(" << node_var_name(dag[i].operands[0]) << ");\n";
                out << "        float sz = sinf(" << node_var_name(dag[i].operands[0]) << ");\n";
                out << "        " << node_var_name(i) << "[0][0] = cz; " << node_var_name(i) << "[0][1] = -sz; " 
                    << node_var_name(i) << "[0][2] = 0.0f; " << node_var_name(i) << "[0][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[1][0] = sz; " << node_var_name(i) << "[1][1] = cz; " 
                    << node_var_name(i) << "[1][2] = 0.0f; " << node_var_name(i) << "[1][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[2][0] = 0.0f; " << node_var_name(i) << "[2][1] = 0.0f; " 
                    << node_var_name(i) << "[2][2] = 1.0f; " << node_var_name(i) << "[2][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[3][0] = 0.0f; " << node_var_name(i) << "[3][1] = 0.0f; " 
                    << node_var_name(i) << "[3][2] = 0.0f; " << node_var_name(i) << "[3][3] = 1.0f;\n";
                out << "    }\n";
                break;
            }
            case NodeKind::RotAxis: {
                out << "    {\n";
                out << "        float ax = " << node_var_name(dag[i].operands[0]) << ";\n";
                out << "        float ay = " << node_var_name(dag[i].operands[1]) << ";\n";
                out << "        float az = " << node_var_name(dag[i].operands[2]) << ";\n";
                out << "        float ang = " << node_var_name(dag[i].operands[3]) << ";\n";
                out << "        float len = sqrtf(ax*ax + ay*ay + az*az);\n";
                out << "        if (len > 1e-6f) { ax /= len; ay /= len; az /= len; }\n";
                out << "        float c = cosf(ang), s = sinf(ang), c1 = 1.0f - c;\n";
                out << "        " << node_var_name(i) << "[0][0] = c + ax*ax*c1; " << node_var_name(i) << "[0][1] = ax*ay*c1 - az*s; " << node_var_name(i) << "[0][2] = ax*az*c1 + ay*s; " << node_var_name(i) << "[0][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[1][0] = ay*ax*c1 + az*s; " << node_var_name(i) << "[1][1] = c + ay*ay*c1; " << node_var_name(i) << "[1][2] = ay*az*c1 - ax*s; " << node_var_name(i) << "[1][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[2][0] = az*ax*c1 - ay*s; " << node_var_name(i) << "[2][1] = az*ay*c1 + ax*s; " << node_var_name(i) << "[2][2] = c + az*az*c1; " << node_var_name(i) << "[2][3] = 0.0f;\n";
                out << "        " << node_var_name(i) << "[3][0] = 0.0f; " << node_var_name(i) << "[3][1] = 0.0f; " << node_var_name(i) << "[3][2] = 0.0f; " << node_var_name(i) << "[3][3] = 1.0f;\n";
                out << "    }\n";
                break;
            }
            case NodeKind::Translate: {
                int tx = dag[i].operands[0];
                int ty = dag[i].operands[1];
                int tz = dag[i].operands[2];
                out << "    " << node_var_name(i) << "[0][0] = 1.0f; " << node_var_name(i) << "[0][1] = 0.0f; " << node_var_name(i) << "[0][2] = 0.0f; " << node_var_name(i) << "[0][3] = " << node_var_name(tx) << ";\n";
                out << "    " << node_var_name(i) << "[1][0] = 0.0f; " << node_var_name(i) << "[1][1] = 1.0f; " << node_var_name(i) << "[1][2] = 0.0f; " << node_var_name(i) << "[1][3] = " << node_var_name(ty) << ";\n";
                out << "    " << node_var_name(i) << "[2][0] = 0.0f; " << node_var_name(i) << "[2][1] = 0.0f; " << node_var_name(i) << "[2][2] = 1.0f; " << node_var_name(i) << "[2][3] = " << node_var_name(tz) << ";\n";
                out << "    " << node_var_name(i) << "[3][0] = 0.0f; " << node_var_name(i) << "[3][1] = 0.0f; " << node_var_name(i) << "[3][2] = 0.0f; " << node_var_name(i) << "[3][3] = 1.0f;\n";
                break;
            }
            case NodeKind::MatMul: {
                int a = dag[i].operands[0];
                int b = dag[i].operands[1];
                out << "    for (int r = 0; r < 4; ++r) {\n";
                out << "        for (int c = 0; c < 4; ++c) {\n";
                out << "            float sum = 0.0f;\n";
                out << "            for (int k = 0; k < 4; ++k) {\n";
                out << "                sum += " << node_var_name(a) << "[r][k] * " << node_var_name(b) << "[k][c];\n";
                out << "            }\n";
                out << "            " << node_var_name(i) << "[r][c] = sum;\n";
                out << "        }\n";
                out << "    }\n";
                break;
            }
            case NodeKind::MatVecMul: {
                int mat = dag[i].operands[0];
                int vec = dag[i].operands[1];
                out << "    for (int r = 0; r < 4; ++r) {\n";
                out << "        float sum = 0.0f;\n";
                out << "        for (int c = 0; c < 4; ++c) {\n";
                out << "            sum += " << node_var_name(mat) << "[r][c] * " << node_var_name(vec) << "[c];\n";
                out << "        }\n";
                out << "        " << node_var_name(i) << "[r] = sum;\n";
                out << "    }\n";
                break;
            }
            case NodeKind::SubVec3: {
                int vec4_node = dag[i].operands[0];
                out << "    " << node_var_name(i) << "[0] = " << node_var_name(vec4_node) << "[0];\n";
                out << "    " << node_var_name(i) << "[1] = " << node_var_name(vec4_node) << "[1];\n";
                out << "    " << node_var_name(i) << "[2] = " << node_var_name(vec4_node) << "[2];\n";
                break;
            }
            case NodeKind::Dot: {
                int a = dag[i].operands[0];
                int b = dag[i].operands[1];
                out << "    " << node_var_name(i) << " = " 
                    << node_var_name(a) << "[0] * " << node_var_name(b) << "[0] + "
                    << node_var_name(a) << "[1] * " << node_var_name(b) << "[1] + "
                    << node_var_name(a) << "[2] * " << node_var_name(b) << "[2];\n";
                break;
            }
            default: {
                out << "    // Unhandled node kind: " << static_cast<int>(dag[i].kind) << "\n";
                break;
            }
        }
    }
    
    out << "\n";
    
    // Debug: print all node names and indices
    out << "// DEBUG: Node listing\n";
    for (int i = 0; i < dag.size(); ++i) {
        const Node& n = dag[i];
        out << "// [" << i << "] " << static_cast<int>(n.kind) << " (" << node_var_name(i) << ")\n";
    }
    out << "\n";
    
    // Constraint outputs
    out << "    // Constraint outputs\n";
    for (int c = 0; c < constraint_outputs.size(); ++c) {
        out << "    float g" << c << " = " << node_var_name(constraint_outputs[c]) << ";\n";
    }
    out << "\n";
    
    // Newton-Levenberg-Marquardt iteration
    out << "    // Newton-Levenberg-Marquardt iteration\n";
    out << "    float q_new[" << num_inputs << "];\n";
    out << "    float lambda = 1e-3f;\n";
    out << "    for (int iter = 0; iter < 10; ++iter) {\n";
    out << "        // Re-evaluate constraints and Jacobian at current q\n";
    out << "        // Solve (J^T J + lambda*I) delta = -J^T g\n";
    out << "        // Update q_new = q + delta\n";
    out << "        // Check convergence\n";
    out << "        // Update lambda\n";
    out << "    }\n";
    out << "\n";
    
    // Copy outputs
    out << "    // Copy outputs\n";
    for (int c = 0; c < lower_result.constraint_outputs.size(); ++c) {
        out << "    out_g[" << c << "] = g" << c << ";\n";
    }
    
    out << "}\n";
    
    return out.str();
}

} // namespace cudro